### ISSUE TITLE
Bracket highlighting is bad color on light mode

### ISSUE THREAD

**Issue by mizlan** [uclaacm/TeachLAFrontend#1028]
<img width="191" alt="Screen Shot 2023-04-17 at 8 29 23 AM" src="https://user-images.githubusercontent.com/44309097/232535849-06813895-f3a2-47ad-bc69-8e4e1708fd3a.png">

In the above image there are parentheses around `'red'` but the highlight causes it to appear as white, which has poor contrast with the white background.

Enable light mode by clicking the hamburger menu in the top left and then flicking the switch with a moon on it.

@pravirchugh maybe take a look?

**Comment by pravirchugh** [comment]
Great feedback! I’ll make the change.
