### ISSUE TITLE
Switch Wordmarks + Logos, Colors (Oct 4th)

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/TeachLAFrontend#350]
See uclaacm/teach-la-website#83.

**Comment by mattxwang** [comment]
@lumisphere902

**Comment by reginawang99** [comment]
is there new designs this year, or is the attached PR representative enough? i might be able to take this!

**Comment by reginawang99** [comment]
oh wait is tykoslowski doing this already?

**Comment by mattxwang** [comment]
I'm not sure, you may want to check in with @lumisphere902 or @krashanoff on this progress of this issue? I don't see an open branch/PR

**Comment by mattxwang** [comment]
The footer on the user pane doesn't have the new logo:
<img width="252" alt="Screen Shot 2021-05-08 at 3 50 33 PM" src="https://user-images.githubusercontent.com/14893287/117555564-25358b80-b015-11eb-9672-f6932172d2f2.png">

**Comment by reginawang99** [comment]
@mattxwang i think its there for me?
![image](https://user-images.githubusercontent.com/29292203/117599499-c9473180-b0fe-11eb-9d8c-5c1fb1a51851.png)

**Comment by mattxwang** [comment]
Oh that's my bad then, I had to force-refresh my cache. This is good to close then!
