### ISSUE TITLE
Remove <iframe>s from Output

### ISSUE THREAD

**Issue by krashanoff** [uclaacm/TeachLAFrontend#369]
If you take a look at [our Output component](https://github.com/uclaacm/TeachLAFrontend/blob/master/src/components/Output/Output.js), you'll notice we use `<iframe>`s to render our code output. This is bad. Very bad. At the very least, we should ensure that we can't have malicious code injection.

This ticket, then, will entail a refactor of our code rendering, or at least a refactor of the [Output component](https://github.com/uclaacm/TeachLAFrontend/blob/master/src/components/Output/Output.js).

**Comment by malsf21** [comment]
When I was poking around this last time, https://github.com/fatiherikli/fil seemed like a cleaner implementation of what we were trying to do.
