### ISSUE TITLE
Very hard to click the join us button on the navbar tab on iPhone X due to no home button

### ISSUE THREAD

**Issue by matthewcn56** [uclaacm/TeachLAFrontend#482]
Attempting to click the join us button on the bottom of new iPhones without home button bars brings up the safari tabs, making it near impossible to click the join us form!

**Comment by lumisphere902** [comment]
Is this referring to the static site? Or are you referring to the github link at the bottom of the editor sidebar

**Comment by matthewcn56** [comment]
oops looks like I submitted an issue to the wrong repo
