### ISSUE TITLE
Guest Login

### ISSUE THREAD

**Issue by lumisphere902** [uclaacm/TeachLAFrontend#483]
Currently, we require a login to use the editor, which is fine for teaching classes, but makes it less feasible for one-time events. A guest login would help with that. I know firebase has an anonymous login feature, but have not done extensive research into how that would work with our current systems.

**Comment by mizlan** [comment]
> I know firebase has an anonymous login feature

I am curious is there a reason why firebase is involved? Does each saved buffer need to be associated with some user in the database? I could see the accumulation of many "unnamed" buffers being a problem as time goes on.

**Comment by lumisphere902** [comment]
Currently all of our programs are associated with a user id. If you can find a solution without Firebase, that’s also fine!Thanks,Timothy Poon On Jan 27, 2023, at 8:12 PM, Michael Lan ***@***.***> wrote:﻿

I know firebase has an anonymous login feature

I am curious is there a reason why firebase is involved? Does each saved buffer need to be associated with some user in the database? I could see the accumulation of many "unnamed" buffers being a problem as time goes on.
