### ISSUE TITLE
Handle unicode characters in Python sketches

### ISSUE THREAD

**Issue by lumisphere902** [uclaacm/TeachLAFrontend#521]
This isn't a super pressing issue, but a teacher did encounter a crash when pasting code from google docs due to the smart quotes. The sketch should either work or give an appropriate error message, rather than crash the entire editor.

**Comment by mizlan** [comment]
IMO this is actually probably the MOST pressing issue we have right now.

**Comment by mizlan** [comment]
This is bad because it breaks even if you attempt to refresh / go back in the browser. On my computer, causes the buffer to just be printed directly to the output area instead of being interpreted as it would normally.
