### ISSUE TITLE
this.state.error does not exist in ProfilePanel.js

### ISSUE THREAD

**Issue by TrevorGuo** [uclaacm/TeachLAFrontend#554]
On line 148 of ProfilePanel.js, there is an undeclared state variable "error" that is passed down as a prop into the declaration of ImageSelector.

**Comment by reginawang-db** [comment]
I don't think I'd consider this a bug. 

In class based components for React, you can just random use `this.state.variable` without setting it in the beginning. It's just harder to read and less preferred, but it's not a bug

**Comment by reginawang99** [comment]
I don't think I'd consider this a bug. 

In class based components for React, you can just random use `this.state.variable` without setting it in the beginning. It's just harder to read and less preferred, but it's not a bug
