### ISSUE TITLE
Refactor TextEditor/components/ShareSketchModal.js to a functional component

### ISSUE THREAD

**Issue by lumisphere902** [uclaacm/TeachLAFrontend#557]
https://github.com/uclaacm/TeachLAFrontend/blob/master/src/components/TextEditor/components/ShareSketchModal.js

**Comment by rajdama** [comment]
I can do it.

**Comment by doubleiis02** [comment]
https://github.com/uclaacm/TeachLAFrontend/blob/master/src/components/TextEditor/components/ShareSketchModal.js
