### ISSUE TITLE
Refactor ClassBox into a functional component

### ISSUE THREAD

**Issue by lumisphere902** [uclaacm/TeachLAFrontend#666]
https://github.com/uclaacm/TeachLAFrontend/blob/master/src/components/Classes/components/ClassBox.js

**Comment by peacebonez** [comment]
Hey Timothy, I found this on https://goodfirstissues.com/ and took a stab at it.  Would you be so kind to give me access to push up my branch for a PR?  Thanks!

**Comment by lumisphere902** [comment]
I’ve given you write access now, @peacebonez
