### ISSUE TITLE
bug: add space between "Login" versus "or, create an account" on login page

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/TeachLAFrontend#741]
Not sure when this regressed, but there's currently no space (between Login or the create account CTA) on the login page, which looks a bit awkward:

![Screen Shot 2021-11-17 at 12 08 38 AM](https://user-images.githubusercontent.com/14893287/142160608-2ec2b33e-369c-4ec8-aa2c-f6c1acab174b.png)

Should be a one-liner?

**Comment by nguyenhung15913** [comment]
Can I work on this ?

**Comment by reginawang3495** [comment]
Go for it!
